#General Parameters
input: path to read files. Multiple files should be combined into one file
outdir: path to the output directory
kmer: kmer to be used for normalization, assembly and quantification
normalization: false if you want to skip the normalization step. otherwise true
#Read Characteristics
type: paired/single
interleaved: true/false
readlength: length of the reads given as input. 
inslength: insert-length if the data is paired end 
#Seecer Parameters
seecertmp: tmp folder required for SEECER (required parameter)
jellyfish: path to jellyfish executable (required parameter) 
binfolder: path to seecer bin folder (required parameter)
seecerkmer: kmer used for error correction (default: 17)
#ORNA parameters
ornabase: base threshold of ORNA (default: 1.7)
#KREATION Parameters
kstep: step size required for KREATION execution (default: 2)
kthreshold: d_score cutoff for KREATION (default: 0.01)
kpname: assembler executable name 
kpadditional: 
#Salmon Parameters
libtype: library type for the reads given as input to salmon

##For more information about the parameters, please refer to the manual/readme files of the individual algorithm
