#General Parameters
input: /MMCI/MS/algorithms/work/SOS/AssemblyOutput/SOS/Blood/TransABySS/NormalizedReads/Normalized_1.fa,/MMCI/MS/algorithms/work/SOS/AssemblyOutput/SOS/Blood/TransABySS/NormalizedReads/Normalized_2.fa
outdir: /MMCI/MS/algorithms/work/SOS/AssemblyOutput/SOS/Blood/TransABySS/
kmer: 31
correction: true
normalization: true
#Read Characteristics
type: paired
interleaved: false
readlength: 100
inslength: 200
#Seecer Parameters
seecertmp: /MMCI/MS/algorithms/work/SOS/AssemblyOutput/SOS/A549/TransABySS/tmp/
jellyfish: /MMCI/MS/DeNovoAssembly/work/SOS/Software/SEECER-0.1.3/jellyfish-1.1.11/bin/jellyfish
scriptsfolder: /MMCI/MS/DeNovoAssembly/work/SOS/Software/SEECER-0.1.3/SEECER/bin/
seecerdir: /MMCI/MS/DeNovoAssembly/work/SOS/Software/SEECER-0.1.3/SEECER/bin/
seecerkmer: 17
#ORNA parameters
ornabase: 1.7
#KREATION Parameters
kstep: 2
kthreshold: 0.01
kpname: transabyss
kpadditional: 
#Salmon Parameters
#Program Name
