#General Parameters
input: /MMCI/MS/algorithms/work/SOS/SOS/Sample_Data/SRR027877-small-p1.fastq,/MMCI/MS/algorithms/work/SOS/SOS/Sample_Data/SRR027877-small-p2.fastq
outdir: /MMCI/MS/algorithms/work/SOS/SOS/TestOutput/
kmer: 21
normalization: true
#Read Characteristics
type: paired
interleaved: false
readlength: 30
inslength: 200
#Seecer Parameters
seecertmp: /MMCI/MS/algorithms/work/SOS/AssemblyOutput/SOS/A549/TransABySS/tmp/
jellyfish: /MMCI/MS/DeNovoAssembly/work/SOS/Software/SEECER-0.1.3/jellyfish-1.1.11/bin/jellyfish
scriptsfolder: /MMCI/MS/DeNovoAssembly/work/SOS/Software/SEECER-0.1.3/SEECER/bin/
seecerdir: /MMCI/MS/DeNovoAssembly/work/SOS/Software/SEECER-0.1.3/SEECER/bin/
seecerkmer: 17
#ORNA parameters
ornabase: 1.7
#KREATION Parameters
kstep: 2
kthreshold: 0.01
kpname: transabyss
kpadditional: 
#Salmon Parameters
libtype: "IU"
